[google_sheets]
type = "service_account"
project_id = "course-registration-461012"
private_key_id = "219df665cf00bb64287ba92f530232db372d0954"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDSRnUKxPeU5Amx
NOQK3umzJ22nae3E1U2xl4vjPuI6ef/IjRpWiws+NZygdIh/c7XBb5htKFNklauS
HLAi912sSOltKxhZPxzAUxD0rg4yNZl36zCOdRYVgfpm/HEz2E5V0kD7ofOBMKTW
Cf1fUnffTXy6BxUHEDYEJVPzYJK1hRnFNuXxz7oGwUxKOk/UKVSxNLGD1HDNK+LO
rUOuIRtAFXoizOtdBjHKxzWgqBlQ3+bq1XOsRbwG6/je8snhf6wjeLoY2PXCs7IZ
pTAPoJekWbh80+6334Qh9yyNaTp6kOcZIpQOL+WlpXuYctrRu1uGgk66N6gcUTMS
29z/C+uhAgMBAAECggEALlPVn5zLy2L+e6tifr6kEJOkRhlBiHdSWclAyb1mDGoq
nn53u6phRzs/zBSsHk8UDi22x0ILs9KFBHrzxVZLYcYfS3fl7sNYF2J20g6QBfrBu
ncow/s3M6fVyYta3ypvCGOcRMCuSgiJsWBg5HY4QA4xLoYvgCev7oV7t9poZlbFZT
hXUNJoXhdifn9GJiDAbWfLdTZp2zjWCpOPYxhRCuRt40mnGiswVUEk8FELTpXiD0
RyHXNV2WNrRAw8Hq29y7wtTvTpy1ipHCZp9Wbc4+6sV24dmbeD6A4uLZXLaSfc33
6s3NH4BokMfAg5egX8D+5cWgiakEhDKu+52z2ia+jQKBgQDyRAaO0cBVdKlx+sh6
PBc9A0DJat84jsIyizcOk6cqzhPYKyBxpZ/NiWoI1rdKH416hV4p2BJ8wM17eslw
HEKMh3eirYlJyzhXPTaVbfcBcMNSuNqM3HBBAz7Lr4dDslicCHYGTaVOjXr2KK2y
/A8KShvnD9KNMbRu7lC3mY67uwKBgQDeMig6IHwu1MSuNhXKoTilRvtMQQHyWggz
HaeO/Ry+3PqsnI5nOvjWehRw27TPfkyDH9bPb8zY99DzAqLAzVAi7ryZVUpis9Hb
5DhVEzoyEENW+SwnlQMybex7U8lnlwL8Gc9StOa2fY6VMTeQ+63dsfl3wlaHNLyo
qAPps/NKUwKBgQC9h5h1zQSiFjWl1ONYNYCcm9noeXKOpaipsB3vinYCV9xQhlTI
dCFTxAgvSAN2ur6NNp9XLxIvhQp8arACxCkQFb7zhr3b/F9kaKA2QSQ3fUdhhPp9
rssnIWnUIcs5m+IUl8312nLTxH2I7IQPfYAqtZWkq8015sfY7Ro6uKhglwKBgQCk
Pnc14GVrSKPKEviwu9PfeESx7Su/NYXyIu2E6NyiyT4S8fbhn9no0Hzjn8RbzIRK
OPLUi1Pk3ep6d2xPEHU4HTkULtO5eiqaXGy3lmriLttYIv/ckm22jULNNvYduKbg
K0PxYv9Xzh/jcGoepauzwKcjO2gysWzzTp711ar1OQKBgQDTJvFkGdX7r0m6wo3l
4nHT2xDVHeliRLX0h9UyUYgAmZc2mEFBHsev3h+pSSgryJ9hXbGadn/gJb7DT7Tw
NYPoxC6FV+1ghwEaRB7CnllZNwFKWFwDglClivEXCc+rSNQMWz45lpFPaD/QDhqE
gHw5s7UwYNwcy4CHxRUfRuGiug==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-bot@course-registration-461012.iam.gserviceaccount.com"
client_id = "101089007549914019550"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot@course-registration-461012.iam.gserviceaccount.com"
universe_domain = "googleapis.com"