[google_sheets]
type = "service_account"
project_id = "course-registration-461012"
private_key_id = "219df665cf00bb64287ba92f530232db372d0954"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIE…
…uyg==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-bot@course-registration-461012.iam.gserviceaccount.com"
client_id = "101089007549914019550"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot@course-registration-461012.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
